line-length = 100

# Базовый набор правил
[lint]
select = [
    "E",    # PEP8 ошибки (отступы, пробелы и т.д.)
    "W",    # PEP8 предупреждения
    "F",    # pyflakes (логические ошибки, неиспользуемые импорты)
    "I",    # isort (сортировка импортов)
]

# Игнорируем только самые раздражающие правила
ignore = [
    "E501",  # разрешаем длинные строки до 100 символов
    "E402",  # разрешаем импорты не в начале файла (иногда нужно)
]


# Не трогаем служебные папки
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "env",
    ".venv",
    "dist",
    "build",
]